CREATE DATABASE IF NOT EXISTS bansos_desa;
USE bansos_desa;

CREATE TABLE IF NOT EXISTS bansos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    nama_prov VARCHAR(100) NOT NULL, 
    nama_kab VARCHAR(100) NOT NULL,
    pekerjaan VARCHAR(100) NOT NULL,
    tanggungan INT NOT NULL,
    jumlah_anak INT NOT NULL,
    penghasilan_per_bulan DECIMAL(12,2) NOT NULL,
    status_kelayakan ENUM('Layak','Tidak Layak') NOT NULL,
    alasan VARCHAR(255) NOT NULL
);

-- Menyimpan hasil prediksi user
CREATE TABLE IF NOT EXISTS hasil_prediksi (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100) NOT NULL,
    pekerjaan VARCHAR(100) NOT NULL,
    tanggungan INT NOT NULL,
    jumlah_anak INT NOT NULL,
    penghasilan_per_bulan DECIMAL(12,2) NOT NULL,
    hasil_prediksi ENUM('Layak','Tidak Layak') NOT NULL,
    nilai_k INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

TRUNCATE TABLE bansos;

INSERT INTO bansos (nama, nama_prov, nama_kab, pekerjaan, tanggungan, jumlah_anak, penghasilan_per_bulan, status_kelayakan, alasan) VALUES
('ABIDIN', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 4, 3, 375000, 'Layak', 'Data KNN'),
('JUBAEDAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 5, 2, 225000, 'Layak', 'Data KNN'),
('ELMINAWATI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 1, 0, 375000, 'Layak', 'Data KNN'),
('BAIQ EKA ANGGRAINI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 2, 1, 600000, 'Layak', 'Data KNN'),
('RUMIAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 1, 0, 375000, 'Layak', 'Data KNN'),
('NIKMAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 2, 0, 725000, 'Tidak Layak', 'Data KNN'),
('SUWARDI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 5, 0, 600000, 'Layak', 'Data KNN'),
('NARIMIN', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 4, 1, 875000, 'Layak', 'Data KNN'),
('HAIRUNI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 5, 4, 450000, 'Layak', 'Data KNN'),
('JUMAKYAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 5, 2, 1425000, 'Layak', 'Data KNN'),
('SAKNAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 1, 0, 600000, 'Tidak Layak', 'Data KNN'),
('RETIAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 4, 2, 600000, 'Layak', 'Data KNN'),
('BAIQ MARTINI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 4, 3, 975000, 'Layak', 'Data KNN'),
('SAHRAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 3, 0, 600000, 'Layak', 'Data KNN'),
('NURUL AINI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 2, 1, 500000, 'Layak', 'Data KNN'),
('MAESARAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 5, 4, 225000, 'Layak', 'Data KNN'),
('LUKMAN SURYADI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 2, 1, 725000, 'Layak', 'Data KNN'),
('KARTINI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 3, 0, 600000, 'Layak', 'Data KNN'),
('RIANA', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 6, 3, 225000, 'Layak', 'Data KNN'),
('MISRAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 3, 0, 375000, 'Layak', 'Data KNN'),
('ENDANG FITRIANI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 4, 1, 375000, 'Layak', 'Data KNN'),
('MANIAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 3, 0, 225000, 'Layak', 'Data KNN'),
('ANISAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 5, 4, 725000, 'Layak', 'Data KNN'),
('FARIDAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 3, 1, 375000, 'Layak', 'Data KNN'),
('MURIAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 4, 2, 375000, 'Layak', 'Data KNN'),
('SAHDAN', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 4, 3, 975000, 'Layak', 'Data KNN'),
('SENIWATI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 1, 0, 375000, 'Layak', 'Data KNN'),
('AWANAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 6, 2, 225000, 'Layak', 'Data KNN'),
('FITRIANINGSIH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 3, 2, 725000, 'Layak', 'Data KNN'),
('RANI MAHARANI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'PNS', 3, 1, 1100000, 'Tidak Layak', 'Data KNN'),
('DENI RAMEDAN', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 1, 0, 600000, 'Layak', 'Data KNN'),
('SITI JUMA INAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 5, 2, 750000, 'Layak', 'Data KNN'),
('ERNAWATI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 5, 2, 600000, 'Layak', 'Data KNN'),
('SARISAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 1, 0, 950000, 'Tidak Layak', 'Data KNN'),
('SAINAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 3, 2, 225000, 'Layak', 'Data KNN'),
('HARTUTI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 1, 0, 1200000, 'Tidak Layak', 'Data KNN'),
('BAIQ HERAWATI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 3, 1, 225000, 'Layak', 'Data KNN'),
('MUNISAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'PNS', 5, 3, 1200000, 'Layak', 'Data KNN'),
('MURNAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 1, 0, 600000, 'Tidak Layak', 'Data KNN'),
('SALMIAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 2, 1, 375000, 'Layak', 'Data KNN'),
('SAKILAWATI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 1, 0, 875000, 'Tidak Layak', 'Data KNN'),
('SALATIAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 4, 0, 825000, 'Layak', 'Data KNN'),
('MULIANI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 1, 0, 600000, 'Layak', 'Data KNN'),
('ISTIHARAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 1, 0, 600000, 'Tidak Layak', 'Data KNN'),
('MARTIAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 4, 2, 225000, 'Layak', 'Data KNN'),
('SITI HAJAR', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pegawai Tetap', 3, 1, 1100000, 'Tidak Layak', 'Data KNN'),
('HUDRIAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 3, 1, 225000, 'Layak', 'Data KNN'),
('MAHNIM', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 6, 0, 375000, 'Layak', 'Data KNN'),
('LALU RUSLAN', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 5, 1, 375000, 'Layak', 'Data KNN'),
('SRI HANDAYANI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 5, 1, 600000, 'Layak', 'Data KNN'),
('SAKNAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 6, 1, 375000, 'Layak', 'Data KNN'),
('SURIANI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'PNS', 5, 1, 1325000, 'Layak', 'Data KNN'),
('SAPURAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 3, 0, 600000, 'Layak', 'Data KNN'),
('MUNAWARAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 2, 1, 500000, 'Layak', 'Data KNN'),
('SUMIATI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 3, 1, 600000, 'Layak', 'Data KNN'),
('SARAKYAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 3, 1, 1100000, 'Layak', 'Data KNN'),
('MUHIR', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Petani Kecil', 2, 1, 600000, 'Layak', 'Data KNN'),
('MASIAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'PNS', 1, 0, 1200000, 'Tidak Layak', 'Data KNN'),
('NYAMAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pegawai Tetap', 1, 0, 1200000, 'Tidak Layak', 'Data KNN'),
('MISLAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pedagang', 1, 0, 1325000, 'Tidak Layak', 'Data KNN'),
('NURHAYATI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Pengangguran', 1, 0, 225000, 'Layak', 'Data KNN'),
('SAKMAH', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 2, 0, 600000, 'Layak', 'Data KNN'),
('AHMAD SAHRI', 'NUSA TENGGARA BARAT', 'KOTA MATARAM', 'Buruh Harian', 5, 3, 600000, 'Layak', 'Data KNN');
